### ISSUE TITLE
Code breaks if you click the icon inside the button

### ISSUE THREAD

**Issue by machty** [logicalguess/rx-state-machine#1]
In the code you write `return ev.target.text.toLocaleLowerCase().trim();` but `ev.target` might be the icon in the button rather than the button itself, and `text` is undefined which causes `toLocaleLowerCase` to be called on `undefined`. 

I'd submit a PR (changing `target` to `currentTarget`) but I'm not sure how far back (to IE8?) you're trying to support, and I didn't want to put in a jQuery solution in case you didn't want that.

Thanks for this example though!

edit `currentTarget` is probably wrong too

**Comment by logicalguess** [comment]
quick fix:

var text = ev.target.text || ev.target.parentNode.text
return text.toLocaleLowerCase().trim();

Thanks for reporting.
